### ISSUE TITLE
Change getClassOptions to return single objects for Semester, Program and Faculty

### ISSUE THREAD

**Issue by ChocolateOverflow** [ChocolateOverflow/VGU-Exercise-6#16]
I'd like to have `getClassOptions` to better reflect the auto-completion. `Lecturers` will now be an array, `SemesterID`, `ProgramID` and `FacultyID` will be single strings.

# SQL
@bacxhoang 

```
procedure getClassOptions(ClassID) -> Lecturer[], Semester, Program, Faculty
```

# Java
@duchai9109 

From the SQL result, get me an array of `lecturers` and single strings `semester`, `program` and `faculty`.

# JS
@dttuoc99 

The response for `getClassOptions` will be as follows

```json
{
  "lecturers": ["1", "a"],
  "semester": "S1",
  "program": "1",
  "faculty": "a"
}
```

**Comment by ChocolateOverflow** [comment]
I've pushed temporary Java code for `getClassOptions` to return single objects of `semester`, `program` & `faculty` for the JS guys, but the SQL & Java code should get updated for better performance.

**Comment by Noe315** [comment]
Finished

**Comment by ChocolateOverflow** [comment]
@bacxhoang You can have 2 separate procedures, 1 to get a list of lecturers and 1 to just get the semester, program & faculty

**Comment by ChocolateOverflow** [comment]
Replacing this with another auto-fill function
