### ISSUE TITLE
Add dropdown options for adding certain items

### ISSUE THREAD

**Issue by ChocolateOverflow** [ChocolateOverflow/VGU-Exercise-6#18]
In the `tables` page, the tables `Class`, `Teaches`, `FacultyInAcademicYear`, `ProgramInFacultyInAcademicYear` and `ModuleInProgramInAcademicYear` should give the user a dropdown list, whose options are to be from the `dump` calls also used in the same page.

**Comment by Noe315** [comment]
Finished
