### ISSUE TITLE
Resource PUT/DELETE (UI)

### ISSUE THREAD

**Issue by ChocolateOverflow** [ChocolateOverflow/VGU-Exercise-6#8]
Implement the Add/Delete buttons for the page `tables`. 

- Details on add (`PUT`) operations: https://github.com/ChocolateOverflow/VGU-Exercise-6/tree/dev/doc/API#put
- Details on delete (`DELETE`) operations: https://github.com/ChocolateOverflow/VGU-Exercise-6/tree/dev/doc/API#delete

**Comment by Noe315** [comment]
`PUT` for the `Academic Year` table is done. We encountered 405 problems when trying with `DELETE`

**Comment by ChocolateOverflow** [comment]
HTTP 405 errors aren't handled by us. It means either you entered the HTTP method wrong or you made the request while the app hadn't finished loading the new application, in which case just wait like 30 seconds after recompiling and copying the WAR file to the `webapps` directory.
