### ISSUE TITLE
Questionnaire answers visualization

### ISSUE THREAD

**Issue by ChocolateOverflow** [ChocolateOverflow/VGU-Exercise-6#9]
Deadline: 07/04/2021

# MySQL (@bacxhoang @NguyenGiaKimThien @TranPhanPhucLong-VGU)

Please create procedures to get the counts of each answer for each question (gender, questions 0-17), 1 procedure per question.

# Java (@ChocolateOverflow , @duchai9109)

The Java team will convert the SQL results to JSON objects.

@duchai9109: SQL -> Java variables
@ChocolateOverflow: Java variables -> JSON objects; implement the API for UI

# UI (@dttuoc99,  @Noe315, @QuanTran4139)

Get answers data and visualize it. The `GET` requests to get the data for each question is as documented (https://github.com/ChocolateOverflow/VGU-Exercise-6/tree/dev/doc/API#getcounts) but with an extra parameter `question` where `question` can be "gender" or a number 0-17 corresponding to the questions. The answers will be formatted as follows:

`resource=gender`:

```json
{
  "M": 0,
  "F": 0,
  "N": 0
}
```

questions 0-17: (some don't have `"N/A"`)

```json
{
  "1": 0,
  "2": 0,
  "3": 0,
  "4": 0,
  "5": 0,
  "N/A": 0,
}
```

(replace the `0` values with real counts)

**Comment by duchai9109** [comment]
I have successfully got the information from database as requested in [documentaion](https://github.com/ChocolateOverflow/VGU-Exercise-6/tree/dev/doc/API#getcounts )

**Comment by ChocolateOverflow** [comment]
@bacxhoang @duchai9109 Please replace `getResponseRate` with `getMaxResponseCount` which returns the sum of all the class sizes with the applied filter.
@dttuoc99 The `getResponseRate` will be replaced accordingly, and the response count is the sum of the answers'  counts.

**Comment by ChocolateOverflow** [comment]
We're adding `Class` and `Lecturer` to the parameters.

**Comment by duchai9109** [comment]
Java: getCounts() getMaxResponseCount() has been upload to github

**Comment by ChocolateOverflow** [comment]
done
